# Generated by Django 5.0.4 on 2024-05-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytable',
            name='domain_name',
            field=models.CharField(default='example.com', max_length=100),
        ),
        migrations.AddField(
            model_name='mytable',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
