# Generated by Django 5.0.6 on 2024-06-17 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj', '0002_mytable_domain_name_mytable_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytable',
            old_name='password',
            new_name='passwor',
        ),
    ]
