# Generated by Django 5.0.6 on 2024-06-17 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj', '0003_rename_password_mytable_passwor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytable',
            old_name='passwor',
            new_name='password',
        ),
    ]
