# Generated by Django 5.0.6 on 2024-06-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj', '0004_rename_passwor_mytable_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytable',
            name='php_version',
            field=models.CharField(default='7.4', max_length=10),
        ),
    ]
