# Generated by Django 5.0.6 on 2024-07-09 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj', '0006_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=100)),
                ('ftp_username', models.CharField(max_length=100)),
                ('ftp_password', models.CharField(max_length=100)),
                ('php_version', models.CharField(max_length=10)),
                ('database_allowed', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj.customer')),
            ],
        ),
    ]
